<?PHP
global $fd_color_1, $fd_color_2, $global_user, $pagename_up, $devel, $fd_color_4, $my_home_color, $global_jobinfo_id;
$GLOBALS['contact_view_js'] = 'Y';
$jobinfo_id = $global_jobinfo_id;

$today=date('m-d-Y');
$jobinfo=getone("select * from jobinfo where jobinfo_id = '$jobinfo_id'");

if ($dailylog_id=="") die("Invalid log selection error!");
$dailylog_id=addslashes($dailylog_id);
$dailylog_info=getone("select * from dailylog where dailylog_id = '$dailylog_id'");
$creator_info=getone("select * from contacts where contacts_id = '$dailylog_info->creator_id'");
$dailylog_entry_info='';

if (empty($dailylog_entries_id))
    $dailylog_entries_id = "new";
else
{
    $sql = "select * from dailylog_entries where dailylog_entries_id = '$dailylog_entries_id'";
    $result = mysql_query( $sql );
    $dailylog_entry_info = mysql_fetch_object($result);
}

$dateArray = explode("-",$dailylog_info->work_date);
$date = $dateArray[1] . "/" . $dateArray[2] . "/" . $dateArray[0];

require_once("header.phtml");

?>
<div class="noprint" id="my_jobs_drop" onmouseout="hide_my_jobs();" onmouseover="show_my_jobs();"><b>Loading List..</b><br>please wait</div>
<div class="noprint" id="recent_jobs_drop" onmouseout="hide_recent_jobs();" onmouseover="show_recent_jobs();"><b>Loading List..</b><br>please wait</div>
<div class="flexContainer">
    <div class="noprint" style="" id="fd_my_home_nav_button">
            <a href="/global/front_desk?mode=my_home">
                My Home
            </a>
    </div>
    <div id="recent_jobs_button" onmouseover="show_recent_jobs();" onmouseout="hide_recent_jobs();">
        <span>
            Recent Jobs
        </span>
    </div>
    <div id="my_jobs_button" onmouseover="show_my_jobs();" onmouseout="hide_my_jobs();">
        <span>
            My Jobs
        </span>
    </div>
    <div id="job_search_header">
        <form name="job_jump" title="Enter job # to go directly to it" method="post" action="/global/front_desk/">
            <label for="contract_num">Load job:</label>
            <input type="hidden" name="mode" value="fd_job_jump" />
            <input type="text" size="6" name="contract_num" id="contract_num" onchange="submit();" />
            <a href="javascript:open_job_search()">Search</a>
        </form>
    </div>
    <div id="login_status_header">
        <?php
            echo "Logged in as ". $global_user->login_name . " <a href=$pagename?kill_session_info=1><font color=blue>Log Off</font></a>";
            
            //if (AccessControl::isAdmin($global_user->contacts_id))
            //{
                ?>
                <!-- <div style="padding: 0px; width: 24px; position: absolute; top: 5px;"><center><img border=0 src="/images/lightbulb_small.png"></center></div>
                <div style="padding: 0px; width: 24px; position: absolute; top: 7px;"><center>?</center></div> -->
                <?php
            //}       
        ?>
    </div>
</div>

<?php
echo "<div id=\"phone_book\" style=\"z-index: 1; display: none; position: absolute; right: 0px;\"></div>
<div id=\"sub_phases\" style=\"z-index: 1; overflow: auto; display: none; position: absolute; right: 0px;\"></div>
<div id=\"material_phases\" style=\"z-index: 1; overflow: auto; display: none; position: absolute;\"></div>
<div id=\"labor_phases\" style=\"z-index: 1; overflow: auto; display: none; position: absolute;\"></div>
<div class=noprint onclick=\"toggle_project_team($jobinfo->jobinfo_id)\" id=\"phone_book_button\" style=\"border-left: 1px solid black; padding: 4px; cursor: hand; cursor: pointer; float: right;\"><font size=-1 color=blue><b>Project Team</b></font></div>
<div class=noprint onclick=\"show_sub_phases($jobinfo->jobinfo_id)\" id=\"sub_phases_button\" style=\"border-left: 1px solid black; padding: 4px; cursor: hand; cursor: pointer; float: right;\"><font size=-1 color=blue><b>Sub Phases</b></font></div>
<div class=noprint onclick=\"show_material_phases($jobinfo->jobinfo_id)\" id=\"material_phases_button\" style=\"border-left: 1px solid black; padding: 4px; cursor: hand; cursor: pointer; float: right;\"><font size=-1 color=blue><b>Material Phases</b></font></div>
<div class=noprint onclick=\"show_labor_phases($jobinfo->jobinfo_id)\" id=\"labor_phases_button\" style=\"border-left: 1px solid black; padding: 4px; cursor: hand; cursor: pointer; float: right;\"><font size=-1 color=blue><b>Labor Phases</b></font></div>
<div class=noprint style=\"float: left; padding: 2px;\"><b>$jobinfo->contract_num&nbsp;-&nbsp;$jobinfo->display_name</b></div>
";
//flush();
if ($jobinfo->weather_station_code!="")
{
	//$jobinfo=check_weather_data($jobinfo);
	$weather_string=standard_weather_string($jobinfo);
	$weather_string=ereg_replace(" ","&nbsp;",$weather_string);
    $weather_string=ereg_replace("Error updating weather data for job " . $jobinfo->jobinfo_id,"",$weather_string);
    //Error updating weather data for job 
    //die( $weather_string );
	echo "<div class=noprint style=\"overflow: hidden; text-align: right; border-left: 1px solid black; padding: 4px; cursor: hand; cursor: pointer;\"><font size=-1>$weather_string</font></div>";
}

?>

<div id="fd_left_nav">

<?php

$mouseovercolor="blue";
$mouseoutcolor="";
$selectedcolor="white";
$jobinfo_id=addslashes($jobinfo_id);

$new_tasks_style="";
$task_summary="";
$pal_active=getone("select sum(1) as total from pal_buddies where jobinfo_id = '$jobinfo_id' and owner_id = '$global_user_id' and status = 'active' and pass_signed_off = 'N'");
if ($pal_active->total!="") {
$pal_new=getone("select sum(1) as total from pal_buddies where jobinfo_id = '$jobinfo_id' and owner_id = '$global_user_id' and status = 'active' and viewed = 'N'");
if ($pal_new->total=="") {
	$pal_new->total='0';
	} else {
	$new_tasks_style="border: 1px solid red; background: yellow;";
	}
$task_summary="<font size=-1><i>&nbsp;($pal_new->total/$pal_active->total)</i></font>";
}

if ($current_app=='front_desk') $class="selectnav";
else $class="normnav";

echo "
<div onmouseover=my_tasks_menu_hold() onmouseout=my_tasks_menu_release() id=\"my_tasks\" style=\"z-index: 2; left: 200px; top: 200px; border: 0px solid black; max-height: 600; overflow: auto; max-width: 400px; background: #ffffff; position: absolute; display: none;\"></div>
<div onmouseover=my_tasks_menu_hold() onmouseout=my_tasks_menu_release() id=\"my_task_items_div\" style=\"z-index: 2; border: 0px solid black; max-height: 600; overflow: auto; max-width: 400px; background: #ffffff; position: absolute; display: none;\"></div>
<div onmouseover=my_tasks_menu_hold() onmouseout=my_tasks_menu_release() id=\"my_pal_details_div\" style=\"z-index: 2; border: 0px solid black; max-height: 600; overflow: auto; max-width: 400px; background: #ffffff; position: absolute; display: none;\"></div>
<table class=noprint width=100%>
<tr class=noprint><td id=\"fd_fd_nav_button\" class=\"$class\" onclick=\"document.location='/global/front_desk$devel/?mode=main';\">Front Desk</td>
<td class=normnav style=\"$new_tasks_style\" id=\"my_tasks_nav_button\" onclick=\"toggle_my_tasks_div($jobinfo_id)\">My Tasks$task_summary
</td>";

$onclick_base="document.location='/global/front_desk$devel/";


if ($devel=="")
{
	$res=@mysql_query("select * from front_desk_job_applications natural join front_desk_applications where jobinfo_id = '$jobinfo_id' and front_desk_applications.devel_only = 'N' order by sort_priority,app_short_description");
}
else
{
	$res=@mysql_query("select * from front_desk_job_applications natural join front_desk_applications where jobinfo_id = '$jobinfo_id' order by sort_priority,app_short_description");
}

while($row=@mysql_fetch_object($res)) {
$onclick=$onclick_base . "$row->app_name$devel/'";$class="normnav";
if ($current_app==$row->app_name) $class="selectnav";
//if ($row->app_short_description=="OIC Log") {
//	if ($global_jobinfo->oic_prefix!="") $row->app_short_description=$global_jobinfo->oic_prefix . " Log";
//	}
$row->app_short_description=ereg_replace(" ","&nbsp;",$row->app_short_description);
echo "<td class=\"$class\" onclick=\"$onclick\">$row->app_short_description</td>";
}

$app='pal';$onclick=$onclick_base . "$app$devel/'";$class="normnav";
if ($current_app==$app) { /*$onclick="";*/$class="selectnav"; }
echo "<td class=\"$class\" onclick=\"$onclick\">P.A.L.</td>";

$app='inbound';$onclick=$onclick_base . "$app$devel/'";$class="normnav";
$inbound_scans=scan_count($jobinfo_id);
if ($current_app==$app) { 
$onclick="";$class="selectnav"; 
}
$buttoncolor="";
if ($inbound_scans>0) $buttoncolor=$fd_color_3;
echo "<td class=\"$class\" style=\"background: $buttoncolor;\" onclick=\"$onclick\">Inbound ($inbound_scans)</td>
</table>";
?>

</div>
<div id="application_menu">
    <div id="fd_doc_tools" class=noprint style="float: left;"></div>
    <div id="fd_doc_queue" style="position: absolute; right: 40px; z-index: 4;"></div>
</div>
<div style="background: <? echo $watermark;?>; background-repeat: repeat; vertical-align: top; text-align: left;">

<h1>Daily Log # <?php echo $dailylog_info->log_num;  ?></h1>
<h2><?php echo $dailylog_info->project; ?></h2>
<h3><?php echo $date; ?></h3>
<div>
<?php
    $sql = "SELECT
                    dailylog_entries.*,
                    contacts.first_name,
                    contacts.last_name
                FROM
                    dailylog_entries
                    LEFT OUTER JOIN contacts ON contacts.contacts_id = dailylog_entries.creator_id
                WHERE
                    dailylog_id = '$dailylog_id'";
    $result = mysql_query( $sql );
    while ($row = mysql_fetch_object( $result))
    {
        echo "<div class=\"dailylog_entry\">";
        echo "<div>" . $row->first_name . " " . $row->last_name . ": " . $row->entry_type . " Foreman Log Entry</div>";
        echo "<div><label>Location:</label><span>".$row->location."</span></div>";
        echo "<div><label>Weather:</label><span>".$row->weather."</span></div>";
        echo "<div><label>Work Progress:</label><span>".$row->work_progress."</span></div>";
        echo "<div><label>Materials Recieved:</label><span>".$row->materials_received."</span></div>";
        echo "<div><label>New Hires:</label><span>".$row->new_hires."</span></div>";
        echo "<div><label>New Hire Safety Training:</label><span>".$row->new_hire_safety_training."</span></div>";
        echo "<div><label>Hinderances:</label><span>".$row->hinderances."</span></div>";
        echo "<div><label>Accidents, near misses or safety concerns:</label><span>".$row->accidents."</span></div>";
        echo "<div><a href=\"index.php?mode=dailylog_edit&dailylog_id=".$dailylog_id."&log_status=edit&dailylog_entries_id=".$row->dailylog_entries_id."\">EDIT</a></div>";
        echo "</div>";
    }
?>
</div>
<div>
<?php
$sql = "SELECT 
                sum(`dailylog_entries`.`our_general_foreman_count`) `our_general_foreman_count`,
                sum(`dailylog_entries`.`our_plumbing_foreman_count`) `our_plumbing_foreman_count`,
                sum(`dailylog_entries`.`our_plumbing_journeyman_count`) `our_plumbing_journeyman_count`,
                sum(`dailylog_entries`.`our_plumbing_apprentice_count`) `our_plumbing_apprentice_count`,
                sum(`dailylog_entries`.`our_steamfitter_foreman_count`) `our_steamfitter_foreman_count`,
                sum(`dailylog_entries`.`our_steamfitter_journeyman_count`) `our_steamfitter_journeyman_count`,
                sum(`dailylog_entries`.`our_steamfitter_apprentice_count`) `our_steamfitter_apprentice_count`,
                sum(`dailylog_entries`.`our_laborer_count`) `our_laborer_count`,
                sum(`dailylog_entries`.`our_truck_driver_count`) `our_truck_driver_count`,
                sum(`dailylog_entries`.`our_operating_engineer_count`) `our_operating_engineer_count`,
                sum(`dailylog_entries`.`our_millwright_count`) `our_millwright_count`,
                sum(`dailylog_entries`.`our_carpenter_count`) `our_carpenter_count`,
                sum(`dailylog_entries`.`our_sheetmetal_count`) `our_sheetmetal_count`,
                sum(`dailylog_entries`.`our_sheetmetal_foreman_count`) `our_sheetmetal_foreman_count`,
                sum(`dailylog_entries`.`our_sheetmetal_journeyman_count`) `our_sheetmetal_journeyman_count`,
                sum(`dailylog_entries`.`our_sheetmetal_apprentice_count`) `our_sheetmetal_apprentice_count`,
                sum(`dailylog_entries`.`our_helper_count`) `our_helper_count`,
                sum(`dailylog_entries`.`our_refrigeration_count`) `our_refrigeration_count`,
                sum(`dailylog_entries`.`sub_temperature_control_count`) `sub_temperature_control_count`,
                sum(`dailylog_entries`.`sub_insulation_count`) `sub_insulation_count`,
                sum(`dailylog_entries`.`sub_painter_count`) `sub_painter_count`,
                sum(`dailylog_entries`.`sub_sewer_men_count`) `sub_sewer_men_count`,
                sum(`dailylog_entries`.`sub_electrician_count`) `sub_electrician_count`,
                sum(`dailylog_entries`.`sub_refrigeration_count`) `sub_refrigeration_count`,
                sum(`dailylog_entries`.`sub_air_balance_count`) `sub_air_balance_count`,
                sum(`dailylog_entries`.`sub_sheet_metal_count`) `sub_sheet_metal_count`,
                sum(`dailylog_entries`.`sub_core_drill_count`) `sub_core_drill_count`,
                sum(`dailylog_entries`.`sub_fire_caulk_count`) `sub_fire_caulk_count`,
                sum(`dailylog_entries`.`sub_fire_protection_count`) `sub_fire_protection_count`,
                sum(`dailylog_entries`.`sub_chemical_treatment_count`) `sub_chemical_treatment_count`,
                sum(`dailylog_entries`.`sub_fuel_tank_install_and_piping_count`) `sub_fuel_tank_install_and_piping_count`,
                sum(`dailylog_entries`.`sub_excavation_count`) `sub_excavation_count`,
                sum(`dailylog_entries`.`our_general_foreman_hours`) `our_general_foreman_hours`,
                sum(`dailylog_entries`.`our_plumbing_foreman_hours`) `our_plumbing_foreman_hours`,
                sum(`dailylog_entries`.`our_plumbing_journeyman_hours`) `our_plumbing_journeyman_hours`,
                sum(`dailylog_entries`.`our_plumbing_apprentice_hours`) `our_plumbing_apprentice_hours`,
                sum(`dailylog_entries`.`our_steamfitter_foreman_hours`) `our_steamfitter_foreman_hours`,
                sum(`dailylog_entries`.`our_steamfitter_journeyman_hours`) `our_steamfitter_journeyman_hours`,
                sum(`dailylog_entries`.`our_steamfitter_apprentice_hours`) `our_steamfitter_apprentice_hours`,
                sum(`dailylog_entries`.`our_laborer_hours`) `our_laborer_hours`,
                sum(`dailylog_entries`.`our_truck_driver_hours`) `our_truck_driver_hours`,
                sum(`dailylog_entries`.`our_operating_engineer_hours`) `our_operating_engineer_hours`,
                sum(`dailylog_entries`.`our_millwright_hours`) `our_millwright_hours`,
                sum(`dailylog_entries`.`our_carpenter_hours`) `our_carpenter_hours`,
                sum(`dailylog_entries`.`our_sheetmetal_hours`) `our_sheetmetal_hours`,
                sum(`dailylog_entries`.`our_sheetmetal_foreman_hours`) `our_sheetmetal_foreman_hours`,
                sum(`dailylog_entries`.`our_sheetmetal_journeyman_hours`) `our_sheetmetal_journeyman_hours`,
                sum(`dailylog_entries`.`our_sheetmetal_apprentice_hours`) `our_sheetmetal_apprentice_hours`,
                sum(`dailylog_entries`.`our_helper_hours`) `our_helper_hours`,
                sum(`dailylog_entries`.`our_refrigeration_hours`) `our_refrigeration_hours`,
                sum(`dailylog_entries`.`sub_temperature_control_hours`) `sub_temperature_control_hours`,
                sum(`dailylog_entries`.`sub_insulation_hours`) `sub_insulation_hours`,
                sum(`dailylog_entries`.`sub_painter_hours`) `sub_painter_hours`,
                sum(`dailylog_entries`.`sub_sewer_men_hours`) `sub_sewer_men_hours`,
                sum(`dailylog_entries`.`sub_electrician_hours`) `sub_electrician_hours`,
                sum(`dailylog_entries`.`sub_refrigeration_hours`) `sub_refrigeration_hours`,
                sum(`dailylog_entries`.`sub_air_balance_hours`) `sub_air_balance_hours`,
                sum(`dailylog_entries`.`sub_sheet_metal_hours`) `sub_sheet_metal_hours`, 
                sum(`dailylog_entries`.`sub_core_drill_hours`) `sub_core_drill_hours`,
                sum(`dailylog_entries`.`sub_fire_caulk_hours`) `sub_fire_caulk_hours`,
                sum(`dailylog_entries`.`sub_fire_protection_hours`) `sub_fire_protection_hours`,
                sum(`dailylog_entries`.`sub_chemical_treatment_hours`) `sub_chemical_treatment_hours`,
                sum(`dailylog_entries`.`sub_fuel_tank_install_and_piping_hours`) `sub_fuel_tank_install_and_piping_hours`,
                sum(`dailylog_entries`.`sub_excavation_hours`) `sub_excavation_hours`
            FROM
                `global`.`dailylog_entries`
            WHERE
                dailylog_id = '$dailylog_id'
            ";
        
$result = mysql_query( $sql );
$dailylog_entry_info = mysql_fetch_object( $result );
?>
    	<table id="dailylog_totals" border="1" cellspacing="0" cellpadding="1" style="border: 1px solid black; font-size: 12px; ">
            <tr bgcolor=$fd_color_4><td>
                <b>Our Craft</b>
            </td><td>
                <b>Count</b>
            </td><td>
                <b>Hours</b>
            </td></tr>
            
            <tr><td>
                General Foreman
            </td><td>
                <?php echo $dailylog_entry_info->our_general_foreman_count; ?>
            </td><td>
                <?php echo $dailylog_entry_info->our_general_foreman_hours; ?>
            </td></tr>
            
            <tr><td>
                Plumbing Foreman
            </td><td>
                <?php echo $dailylog_entry_info->our_plumbing_foreman_count; ?>
            </td><td>
                <?php echo $dailylog_entry_info->our_plumbing_foreman_hours; ?>
            </td></tr>
            
            <tr><td>
                Plumbing Journeyman
            </td><td>
                <?php echo $dailylog_entry_info->our_plumbing_journeyman_count; ?>
            </td><td>
                <?php echo $dailylog_entry_info->our_plumbing_journeyman_hours; ?>
            </td></tr>
            
            <tr><td>
                Plumbing Apprentices
            </td><td>
                <?php echo $dailylog_entry_info->our_plumbing_apprentice_count; ?>
            </td><td>
                <?php echo $dailylog_entry_info->our_plumbing_apprentice_hours; ?>
            </td></tr>
            
            <tr><td>
                Steamfitter Foreman
            </td><td>
                <?php echo $dailylog_entry_info->our_steamfitter_foreman_count; ?>
            </td><td>
                <?php echo $dailylog_entry_info->our_steamfitter_foreman_hours; ?>
            </td></tr>
            
            <tr><td>
                Steamfitter Journeyman
            </td><td
                <?php echo $dailylog_entry_info->our_steamfitter_journeyman_count; ?>
            </td><td>
                <?php echo $dailylog_entry_info->our_steamfitter_journeyman_hours; ?>
            </td></tr>
        
            <tr><td>
                Steamfitter Apprentices
            </td><td>
                <?php echo $dailylog_entry_info->our_steamfitter_apprentice_count; ?>
            </td><td
                <?php echo $dailylog_entry_info->our_steamfitter_apprentice_hours; ?>
            </td></tr>
            
            <tr><td>
                Laborers
            </td><td>
                <?php echo $dailylog_entry_info->our_laborer_count; ?>
            </td><td>
                <?php echo $dailylog_entry_info->our_laborer_hours; ?>
            </td></tr>
            
            <tr><td>
                Truck Driver
            </td><td>
                <?php echo $dailylog_entry_info->our_truck_driver_count; ?>
            </td><td>
                <?php echo $dailylog_entry_info->our_truck_driver_hours; ?>
            </td></tr>
            
            <tr><td>
                Operating Engineer
            </td><td>
                <?php echo $dailylog_entry_info->our_operating_engineer_count; ?>
            </td><td>
                <?php echo $dailylog_entry_info->our_operating_engineer_hours; ?>
            </td></tr>
            
            <tr><td>
                Millwright
            </td><td>
                <?php echo $dailylog_entry_info->our_millwright_count; ?>
            </td><td>
                <?php echo $dailylog_entry_info->our_millwright_hours; ?>
            </td></tr>
            
            <tr><td>
                Carpenter
            </td><td>
                <?php echo $dailylog_entry_info->our_carpenter_count; ?>
            </td><td>
                <?php echo $dailylog_entry_info->our_carpenter_hours; ?>
            </td></tr>
            
            <tr><td>
                Sheetmetal
            </td><td>
                <?php echo $dailylog_entry_info->our_sheetmetal_count; ?>
            </td><td>
                <?php echo $dailylog_entry_info->our_sheetmetal_hours; ?>
            </td></tr>
        
            <tr><td>
                Sheetmetal Foreman
            </td><td>
                <?php echo $dailylog_entry_info->our_sheetmetal_foreman_count; ?>
            </td><td>
                <?php echo $dailylog_entry_info->our_sheetmetal_foreman_hours; ?>
            </td></tr>
            
            <tr><td>
                Sheetmetal Journeyman
            </td><td>
                <?php echo $dailylog_entry_info->our_sheetmetal_journeyman_count; ?>
            </td><td>
                <?php echo $dailylog_entry_info->our_sheetmetal_journeyman_hours; ?>
            </td></tr>
            
            <tr><td>
                Sheetmetal Apprentices
            </td><td>
                <?php echo $dailylog_entry_info->our_sheetmetal_apprentice_count; ?>
            </td><td>
                <?php echo $dailylog_entry_info->our_sheetmetal_apprentice_hours; ?>
            </td></tr>
            
            <tr><td>
                Helper
            </td><td>
                <?php echo $dailylog_entry_info->our_helper_count; ?>
            </td><td>
                <?php echo $dailylog_entry_info->our_helper_hours; ?>
            </td></tr>
        
            <tr><td>
                Refrigeration
            </td><td>
                <?php echo $dailylog_entry_info->our_refrigeration_count; ?>
            </td><td>
                <?php echo $dailylog_entry_info->our_refrigeration_hours; ?>
            </td></tr>
        
            <tr bgcolor=$fd_color_4><td>
                <b>Subcontractors</b>
            </td><td>
                <b>Count</b>
            </td><td>
                <b>Hours</b>
            </td></tr>
            
            <tr><td>
                Temperature Control
            </td><td>
                <?php echo $dailylog_entry_info->sub_temperature_control_count; ?>
            </td><td>
                <?php echo $dailylog_entry_info->sub_temperature_control_hours; ?>
            </td></tr>
            
            <tr><td>
                Insulation
            </td><td>
                <?php echo $dailylog_entry_info->sub_insulation_count; ?>
            </td><td>
                <?php echo $dailylog_entry_info->sub_insulation_hours; ?>
            </td></tr>
            
            <tr><td>
                Painters
            </td><td>
                <?php echo $dailylog_entry_info->sub_painter_count; ?>
            </td><td>
                <?php echo $dailylog_entry_info->sub_painter_hours; ?>
            </td></tr>
            
            <tr><td>
                Sewer Men
            </td><td>
                <?php echo $dailylog_entry_info->sub_sewer_men_count; ?>
            </td><td>
                <?php echo $dailylog_entry_info->sub_sewer_men_hours; ?>
            </td></tr>
            
            <tr><td>
                Electrician
            </td><td>
                <?php echo $dailylog_entry_info->sub_electrician_count; ?>
            </td><td>
                <?php echo $dailylog_entry_info->sub_electrician_hours; ?>
            </td></tr>
            
            <tr><td>
                Refrigeration
            </td><td>
                <?php echo $dailylog_entry_info->sub_refrigeration_count; ?>
            </td><td>
                <?php echo $dailylog_entry_info->sub_refrigeration_hours; ?>
            </td></tr>
        
            <tr><td>
                Air Balance
            </td><td>
                <?php echo $dailylog_entry_info->sub_air_balance_count; ?>
            </td><td>
                <?php echo $dailylog_entry_info->sub_air_balance_hours; ?>
            </td></tr>
            
            <tr><td>
                Sheet Metal
            </td><td>
                <?php echo $dailylog_entry_info->sub_sheet_metal_count; ?>
            </td><td>
                <?php echo $dailylog_entry_info->sub_sheet_metal_hours; ?>
            </td></tr>
        
            <tr><td>
                Core Drill
            </td><td>
                <?php echo $dailylog_entry_info->sub_core_drill_count; ?>
            </td><td>
                <?php echo $dailylog_entry_info->sub_core_drill_hours; ?>
            </td></tr>
        
            <tr><td>
                Fire Caulk
            </td><td>
                <?php echo $dailylog_entry_info->sub_fire_caulk_count; ?>
            </td><td>
                <?php echo $dailylog_entry_info->sub_fire_caulk_hours; ?>
            </td></tr>
        
            <tr><td>
                Fire Protection
            </td><td>
                <?php echo $dailylog_entry_info->sub_fire_protection_count; ?>
            </td><td>
                <?php echo $dailylog_entry_info->sub_fire_protection_hours; ?>
            </td></tr>
        
            <tr><td>
                Chemical Treatment
            </td><td>
                <?php echo $dailylog_entry_info->sub_chemical_treatment_count; ?>
            </td><td>
                <?php echo $dailylog_entry_info->sub_chemical_treatment_hours; ?>
            </td></tr>
        
            <tr><td>
                Fuel Tank Install/Piping
            </td><td>
                <?php echo $dailylog_entry_info->sub_fuel_tank_install_and_piping_count; ?>
            </td><td>
                <?php echo $dailylog_entry_info->sub_fuel_tank_install_and_piping_hours; ?>
            </td></tr>
        
            <tr><td>
                Excavation
            </td><td>
                <?php echo $dailylog_entry_info->sub_excavation_count; ?>
            </td><td>
                <?php echo $dailylog_entry_info->sub_excavation_hours; ?>
            </td></tr>
	</table>
</div>


</div>
<script>
    setTimeout("ajaxManager('load_page','/global/front_desk?mode=my_jobs_menu','my_jobs_drop')",100);
	setTimeout("ajaxManager('load_page','/global/front_desk?mode=recent_jobs_menu','recent_jobs_drop')",200);
</script>