<?PHP
global $fd_color_1, $fd_color_2, $global_user, $pagename_up, $devel, $fd_color_4, $my_home_color, $global_jobinfo_id;
$GLOBALS['contact_view_js'] = 'Y';
$jobinfo_id = $global_jobinfo_id;
require_once("header.phtml");
$today=date('m-d-Y');
$jobinfo_id=addslashes($jobinfo_id);
$jobinfo=getone("select * from jobinfo where jobinfo_id = '$jobinfo_id'");



?>
<div class="noprint" id="my_jobs_drop" onmouseout="hide_my_jobs();" onmouseover="show_my_jobs();"><b>Loading List..</b><br>please wait</div>
<div class="noprint" id="recent_jobs_drop" onmouseout="hide_recent_jobs();" onmouseover="show_recent_jobs();"><b>Loading List..</b><br>please wait</div>
<div class="flexContainer">
    <div class="noprint" style="" id="fd_my_home_nav_button">
            <a href="/global/front_desk?mode=my_home">
                My Home
            </a>
    </div>
    <div id="recent_jobs_button" onmouseover="show_recent_jobs();" onmouseout="hide_recent_jobs();">
        <span>
            Recent Jobs
        </span>
    </div>
    <div id="my_jobs_button" onmouseover="show_my_jobs();" onmouseout="hide_my_jobs();">
        <span>
            My Jobs
        </span>
    </div>
    <div id="job_search_header">
        <form name="job_jump" title="Enter job # to go directly to it" method="post" action="/global/front_desk/">
            <label for="contract_num">Load job:</label>
            <input type="hidden" name="mode" value="fd_job_jump" />
            <input type="text" size="6" name="contract_num" id="contract_num" onchange="submit();" />
            <a href="javascript:open_job_search()">Search</a>
        </form>
    </div>
    <div id="login_status_header">
        <?php
            echo "Logged in as ". $global_user->login_name . " <a href=$pagename?kill_session_info=1><font color=blue>Log Off</font></a>";
            
            //if (AccessControl::isAdmin($global_user->contacts_id))
            //{
                ?>
                <!-- <div style="padding: 0px; width: 24px; position: absolute; top: 5px;"><center><img border=0 src="/images/lightbulb_small.png"></center></div>
                <div style="padding: 0px; width: 24px; position: absolute; top: 7px;"><center>?</center></div> -->
                <?php
            //}       
        ?>
    </div>
</div>

<?php
echo "<div id=\"phone_book\" style=\"z-index: 1; display: none; position: absolute; right: 0px;\"></div>
<div id=\"sub_phases\" style=\"z-index: 1; overflow: auto; display: none; position: absolute; right: 0px;\"></div>
<div id=\"material_phases\" style=\"z-index: 1; overflow: auto; display: none; position: absolute;\"></div>
<div id=\"labor_phases\" style=\"z-index: 1; overflow: auto; display: none; position: absolute;\"></div>
<div class=noprint onclick=\"toggle_project_team($jobinfo->jobinfo_id)\" id=\"phone_book_button\" style=\"border-left: 1px solid black; padding: 4px; cursor: hand; cursor: pointer; float: right;\"><font size=-1 color=blue><b>Project Team</b></font></div>
<div class=noprint onclick=\"show_sub_phases($jobinfo->jobinfo_id)\" id=\"sub_phases_button\" style=\"border-left: 1px solid black; padding: 4px; cursor: hand; cursor: pointer; float: right;\"><font size=-1 color=blue><b>Sub Phases</b></font></div>
<div class=noprint onclick=\"show_material_phases($jobinfo->jobinfo_id)\" id=\"material_phases_button\" style=\"border-left: 1px solid black; padding: 4px; cursor: hand; cursor: pointer; float: right;\"><font size=-1 color=blue><b>Material Phases</b></font></div>
<div class=noprint onclick=\"show_labor_phases($jobinfo->jobinfo_id)\" id=\"labor_phases_button\" style=\"border-left: 1px solid black; padding: 4px; cursor: hand; cursor: pointer; float: right;\"><font size=-1 color=blue><b>Labor Phases</b></font></div>
<div class=noprint style=\"float: left; padding: 2px;\"><b>$jobinfo->contract_num&nbsp;-&nbsp;$jobinfo->display_name</b></div>
";
//flush();
if ($jobinfo->weather_station_code!="")
{
	//$jobinfo=check_weather_data($jobinfo);
	$weather_string=standard_weather_string($jobinfo);
	$weather_string=ereg_replace(" ","&nbsp;",$weather_string);
    $weather_string=ereg_replace("Error updating weather data for job " . $jobinfo->jobinfo_id,"",$weather_string);
    //Error updating weather data for job 
    //die( $weather_string );
	echo "<div class=noprint style=\"overflow: hidden; text-align: right; border-left: 1px solid black; padding: 4px; cursor: hand; cursor: pointer;\"><font size=-1>$weather_string</font></div>";
}

?>

<div id="fd_left_nav">

<?php

$mouseovercolor="blue";
$mouseoutcolor="";
$selectedcolor="white";
$jobinfo_id=addslashes($jobinfo_id);

$new_tasks_style="";
$task_summary="";
$pal_active=getone("select sum(1) as total from pal_buddies where jobinfo_id = '$jobinfo_id' and owner_id = '$global_user_id' and status = 'active' and pass_signed_off = 'N'");
if ($pal_active->total!="") {
$pal_new=getone("select sum(1) as total from pal_buddies where jobinfo_id = '$jobinfo_id' and owner_id = '$global_user_id' and status = 'active' and viewed = 'N'");
if ($pal_new->total=="") {
	$pal_new->total='0';
	} else {
	$new_tasks_style="border: 1px solid red; background: yellow;";
	}
$task_summary="<font size=-1><i>&nbsp;($pal_new->total/$pal_active->total)</i></font>";
}

if ($current_app=='front_desk') $class="selectnav";
else $class="normnav";

echo "
<div onmouseover=my_tasks_menu_hold() onmouseout=my_tasks_menu_release() id=\"my_tasks\" style=\"z-index: 2; left: 200px; top: 200px; border: 0px solid black; max-height: 600; overflow: auto; max-width: 400px; background: #ffffff; position: absolute; display: none;\"></div>
<div onmouseover=my_tasks_menu_hold() onmouseout=my_tasks_menu_release() id=\"my_task_items_div\" style=\"z-index: 2; border: 0px solid black; max-height: 600; overflow: auto; max-width: 400px; background: #ffffff; position: absolute; display: none;\"></div>
<div onmouseover=my_tasks_menu_hold() onmouseout=my_tasks_menu_release() id=\"my_pal_details_div\" style=\"z-index: 2; border: 0px solid black; max-height: 600; overflow: auto; max-width: 400px; background: #ffffff; position: absolute; display: none;\"></div>
<table class=noprint width=100%>
<tr class=noprint><td id=\"fd_fd_nav_button\" class=\"$class\" onclick=\"document.location='/global/front_desk$devel/?mode=main';\">Front Desk</td>
<td class=normnav style=\"$new_tasks_style\" id=\"my_tasks_nav_button\" onclick=\"toggle_my_tasks_div($jobinfo_id)\">My Tasks$task_summary
</td>";

$onclick_base="document.location='/global/front_desk$devel/";


if ($devel=="")
{
	$res=@mysql_query("select * from front_desk_job_applications natural join front_desk_applications where jobinfo_id = '$jobinfo_id' and front_desk_applications.devel_only = 'N' order by sort_priority,app_short_description");
}
else
{
	$res=@mysql_query("select * from front_desk_job_applications natural join front_desk_applications where jobinfo_id = '$jobinfo_id' order by sort_priority,app_short_description");
}

while($row=@mysql_fetch_object($res)) {
$onclick=$onclick_base . "$row->app_name$devel/'";$class="normnav";
if ($current_app==$row->app_name) $class="selectnav";
//if ($row->app_short_description=="OIC Log") {
//	if ($global_jobinfo->oic_prefix!="") $row->app_short_description=$global_jobinfo->oic_prefix . " Log";
//	}
$row->app_short_description=ereg_replace(" ","&nbsp;",$row->app_short_description);
echo "<td class=\"$class\" onclick=\"$onclick\">$row->app_short_description</td>";
}

$app='pal';$onclick=$onclick_base . "$app$devel/'";$class="normnav";
if ($current_app==$app) { /*$onclick="";*/$class="selectnav"; }
echo "<td class=\"$class\" onclick=\"$onclick\">P.A.L.</td>";

$app='inbound';$onclick=$onclick_base . "$app$devel/'";$class="normnav";
$inbound_scans=scan_count($jobinfo_id);
if ($current_app==$app) { 
$onclick="";$class="selectnav"; 
}
$buttoncolor="";
if ($inbound_scans>0) $buttoncolor=$fd_color_3;
echo "<td class=\"$class\" style=\"background: $buttoncolor;\" onclick=\"$onclick\">Inbound ($inbound_scans)</td>
</table>";
?>

</div>
<div id="application_menu">
    <div id="fd_doc_tools" class=noprint style="float: left;"></div>
    <div id="fd_doc_queue" style="position: absolute; right: 40px; z-index: 4;"></div>
</div>
<div style="background: <? echo $watermark;?>; background-repeat: repeat; vertical-align: top; text-align: left;">
<table id="sub_application_main_table" cellpadding=3>
	<thead>
		<tr>
			<td colspan=8>
				<?php
					search_div();
				?>
				<center><b><font size=+1>Daily Log</font></b><br>
				
				<?php
					echo $today;
					$query_search_add=query_search_add_text();
					$query="select * from dailylog where jobinfo_id = '$global_jobinfo_id' and section = '$current_dailylog_section' $query_search_add order by work_date desc, dailylog_id desc";
					$res=@mysql_query($query);

					include("fd_log_paging.phtml");

					echo "<br>
					<a href=javascript:create_new_dailylog('$pagename')><font color=blue>Create New Daily Log</font></a><br>$page_page_insert
					</center>
					</td></tr>
					
					<tr class=floatheader><td>
						&nbsp;
					</td><td>
						<b>Log #</b>
					</td><td>
						<b>Weekday</b>
					</td><td>
						<b>Date</b>
					</td><td>
						<b>Created By</b>
					</td><td>
						<b>Status</b>
					</td><td>
						<b>Weather</b>
					</td><td>
						<b>Hindrances</b>
					</td></tr>
					</thead><tbody class=floatheader>
					";

while ($row=@mysql_fetch_object($res)) {
	$temp_doc_id_query="select * from documents where doc_type = 'dailylog' and section = '$row->section' and app_record_id = '$row->dailylog_id'";
	$temp_doc_info=getoneb($temp_doc_id_query);
	$temp_doc_id=$temp_doc_info->doc_id;
	$file_batch=batch_this_document($temp_doc_id);

	$weekday=date("D",strtotime($row->work_date));
	if ($row->work_hinderances=="") $hind="&nbsp;";
	else $hind='*';
	
	$creator_info=getoneb("select * from contacts where contacts_id = '$row->creator_id'");
	$date=invali_date($row->work_date,'/');
	echo "<tr><td>
			$file_batch
		</td><td>
			<a href=$pagename?mode=dailylog_view&dailylog_id=$row->dailylog_id><font color=blue>$row->log_num</font></a>
		</td><td align=center>
			$weekday
		</td><td>
			$date
		</td><td>
			$creator_info->first_name $creator_info->last_name
		</td><td>
			$row->status
		</td><td>
			$row->weather
		</td><td>
			$hind
		</td></tr>
		";
	}
echo "<tr><td colspan=15 height=100%></td></tr></tbody></table>";
?>	
</div>
<script>
    setTimeout("ajaxManager('load_page','/global/front_desk?mode=my_jobs_menu','my_jobs_drop')",100);
	setTimeout("ajaxManager('load_page','/global/front_desk?mode=recent_jobs_menu','recent_jobs_drop')",200);
</script>