<?
require_once("header.phtml");

require_once("settings.cfg");
require_once("querylib.inc");
require_once("global-auth.inc");

require_once("timesheet_libs.inc");

//if ($global_contacts_id='353'||$global_contacts_id=='4517'||$global_contacts_id='2'||$global_contacts_id='1') die("testing!!!");

if ($global_contacts_id='353'||$global_contacts_id=='4517'||$global_contacts_id='2'||$global_contacts_id='1') include("viewpoint_connect_ro_pr.phtml");
else include("viewpoint_connect_ro.phtml");

require_once("timesheet_include.inc");

$submit_text="Add";
if ($timesheet_time_id=="") {
	$timesheet_time=new bsclass;
	$timesheet_time->workday=escapeshellcmd($workday);
	$new=1;
	}else{
	$new=0;
	if ($timesheet_time_id!="reentry") {
		$timesheet_time_id=escapeshellcmd($timesheet_time_id);
		$timesheet_time=getone("select * from timesheet_time where timesheet_time_id = '$timesheet_time_id'");
		$timesheet_time->workday=invali_date($timesheet_time->workday);
		$submit_text="Change";
		} else {
		$timesheet_time_id="";
		}
	$earnings_code=$timesheet_time->earnings_code;
	}

if ($earnings_code=="") $ec_checked_st="checked";
if ($earnings_code=="1") $ec_checked_st="checked";
if ($earnings_code=="2") $ec_checked_ot="checked";
if ($earnings_code=="3") $ec_checked_dt="checked";


if ($timesheet_time_id=="")
{
	echo "<a href=javascript:expenses();><font color=blue>Mileage/Subsistence/Parking/Travel</font></a><br>";
	if ($current_user->timesheet_allow_ap_entry=='Y')
	{
		echo "
		<a href=$pagename?mode=timesheet_edit&timesheet_mode_new=timesheet_generate_ap_time><font color=blue>Generate AP Time Entries</font></a><br>
		";
	}
}
?>	

<form name="add_time" id="add_time" method="post" action="<?PHP print $pagename; ?>">
<input type="hidden" name="mode" value="timesheet_edit_add_time_verify">
<input type="hidden" name="timesheet_time_id" value="<?PHP print $timesheet_time_id; ?>">
<input type="hidden" name="timesheet_id" id="timesheet_id" value="<?PHP print $timesheet_time->timesheet_id; ?>">
<input type="hidden" name="return_to" value="<?PHP print $return_to; ?>">

<table border="1">
	<tr>
		<td colspan="3" bgcolor="#dddddd" align="center">
			<b>
				<?php print $submit_text . " time for " . $timesheet_time->workday; ?>
				<input type="hidden" name="workday" value="<?PHP print $timesheet_time->workday; ?>">
				for
				<?php print $current_user->first_name . " " . $current_user->last_name; ?>
			</b>
		</td>
	</tr>

	<tr><td colspan="3">
	Employee Number: <?php print $current_user->employee_num; ?>
	<input type="hidden" name="employee_num" value="<?php print $current_user->employee_num; ?>">

	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Shift:
	<select name="shift" id="shift" tabindex="1">
		<?php
			print $timesheet_time->shift_last; 
			if ($timesheet_time_id!="")
				echo "<option>$timesheet_time->shift</option>";
		?>
	<option>1</option>
	<option>2</option>
	<option>3</option>
	</select>
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
	<input type="submit" value="<?PHP print $submit_text; ?>" tabindex="7">
</td></tr>

<tr>
	<td valign="top">
		<a href="javascript:job_help();">
			<font color="black">
				Job Number:
			</font>
		</a>
		<br>
		<input type="text" size="13" name="job_num" id="job_num" value="<?php echo $timesheet_time->job_num; ?>" tabindex="2"><br>
		<input type="hidden" name="job_num_hidden" id="job_num_hidden" value="<?PHP echo $timesheet_time->job_num; ?>" >
		<input type="hidden" name="job_description_hidden" id="job_description_hidden" value="<?PHP echo $timesheet_time->description; ?>" >
		<?PHP recent_jobs($current_user->contacts_id); ?>
	</td><td valign="top">
		<a href="javascript:phase_help();">
			<font color="black">Phase:</font>
		</a>
		<br>
		<input type="hidden" name="phase_value" id="phase_value">
		<select id="phase" name="phase" tabindex="3"></select>
		<br><br>
		<?PHP recent_phases($current_user->contacts_id); ?>
	</td>
	<td valign="top">
		Hours:
		<br>
		<input type="text" size="5" name="hours" value="<?PHP echo $timesheet_time->hours; ?>" tabindex="4">
		<br>
		ST <input type="radio" name="earnings_code" value="1" <?PHP echo $ec_checked_st; ?>><br>
		OT <input type="radio" name="earnings_code" value="2" <?PHP echo $ec_checked_ot; ?>><br>
		DT <input type="radio" name="earnings_code" value="3" <?PHP echo $ec_checked_dt; ?>><br>
	</td>
</tr>
<tr>
	<td colspan="3">
		Notes: <br>
		<textarea name="comments" cols="40" rows="5" scrollbars="no" tabindex="5"><?php echo $timesheet_time->comments; ?></textarea>
	</td>
</tr>
<tr>
	<td colspan="3" align="right">
		<?PHP
			$tmp=date_info($timesheet_time->workday);
			if (($tmp->day_of_week_num==1) && ($timesheet_time_id==""))
				echo "Add entry for entire week: <input type=\"checkbox\" name=\"full_week\">";
		?>
		<input type="button" tabindex="5" id="cancel_button" value="Cancel">
		<input type="submit" tabindex="6" value="<?PHP print $submit_text; ?>">
	</td>
</tr>
</form>
</table>

<?PHP

if ($timesheet_time_id != "")
{
	$dashPosition = strpos ( $timesheet_time->job_num, "-");
	$timesheet_time->job_num = substr($timesheet_time->job_num,0,$dashPosition);
	//die($timesheet_time->phase);
	?>
	<script>
		populatePhaseListValue('<?PHP print $timesheet_time->job_num; ?>','<?PHP print $timesheet_time->phase; ?>');
	</script>	
	<?PHP
}
else if ($timesheet_time->job_num)
{
	?>
	<script>
		populatePhaseList('<?PHP print $timesheet_time->job_num; ?>');
	</script>
	<?PHP
}

?>

<script>

function phase_help()
{
	if (document.add_time.job_num.value=='')
	{
		alert('Error: Please enter a job number first');
	}
	else
	{
		open ('<?PHP print $pagename; ?>?mode=timesheet_phase_popup&job_num=' + document.add_time.job_num.value,'timesheet_popup','height=400,width=500,scrollbars=yes,resizable=yes');
	}
}

function job_help()
{
	open('<?PHP print $pagename; ?>?mode=timesheet_job_popup','timesheet_popup','height=400,width=400,scrollbars=yes,resizable=yes');
}

function expenses()
{
	open('<?PHP print $pagename; ?>?mode=timesheet_edit_expenses_popup&workday=<?PHP print $timesheet_time->workday; ?>','spt_popup','height=400,width=400,scrollbars=yes,resizable=yes');
}

function spt()
{
	open('<?PHP print $pagename; ?>?mode=timesheet_edit_add_spt_popup&workday=<?PHP print $timesheet_time->workday; ?>','spt_popup','height=400,width=400,scrollbars=yes,resizable=yes');
}

function mileage()
{
	open('<?PHP print $pagename; ?>?mode=timesheet_edit_add_mileage_popup&workday=<?PHP print $timesheet_time->workday; ?>','spt_popup','height=400,width=400,scrollbars=yes,resizable=yes');
}
document.add_time.job_num.focus();
</script>

<?PHP
	if ($timesheet_time_id != "")
	{
		?>
		<script>
			function dte(ts_id)
			{
				if (confirm('Are you sure you want to delete this entry?')) document.location='<?PHP print $pagename; ?>?mode=timesheet_edit_time_remove&timesheet_time_id=' + ts_id;
			}
		</script>
		<a href="javascript:dte(<?PHP print $timesheet_time_id; ?>);"><b>DELETE THIS ENTRY</b></a>
		<?PHP
	}
?>