<?
// GPH Cleanup warnings

global $use_odbc;  //set this to true if you're developing on a system with no access to mssql library.

$use_odbc = 0;

$color_4 = isset($fd_color_4) ? $fd_color_4 : '#888';
?>
<!DOCTYPE html>
<head>
<meta http-equiv="X-UA-Compatible" content="chrome=1">
<link rel="icon" type="image/png" href="/favicon.png">

<link rel="stylesheet" type="text/css" href="/css/styles.css" />
<link rel="stylesheet" type="text/css" href="/css/print.css" media="print" />

<script type="text/javascript" src="/javascript/umc_ajax.js"></script>
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<!-- <script type="text/javascript" src="/javascript/jquery.js"></script> -->


<!-- <script type="text/javascript" src="/javascript/dailylog.js"></script> -->

<title><?PHP print $dbdescription; ?></title>
</head>
<body>