<?PHP
// GPH Cleanup warnings
global $use_odbc;  //set this to true if you're developing on a system with no access to mssql library.
$use_odbc = 0;
$color_4 = isset($fd_color_4) ? $fd_color_4 : '#888';
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<head>
<meta http-equiv="X-UA-Compatible" content="chrome=1">
<link rel="icon" type="image/png" href="/favicon.png" />

<link rel="stylesheet" type="text/css" href="/css/styles.css" />
<link rel="stylesheet" type="text/css" href="/css/print.css" media="print" />
<link rel="stylesheet" type="text/css" href="/javascript/jquery-ui-multiselect/jquery.multiselect.css" />
<link rel="stylesheet" type="text/css" href="/javascript/jquery-ui-multiselect/demos/assets/style.css" />
<link rel="stylesheet" type="text/css" href="/javascript/jquery-ui-multiselect/demos/assets/prettify.css" />
<link rel="stylesheet" type="text/css" href="/css/jquery-ui.css" />
<link rel="stylesheet" type="text/css" href="/javascript/jquery-ui-daterangepicker/jquery.comiseo.daterangepicker.css" />

<script type="text/javascript" src="/javascript/umc_ajax.js"></script>
<!-- <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script> -->
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript" src="/javascript/jquery.js"></script>
<script type="text/javascript" src="/javascript/jquery-ui.min.js"></script>
<script type="text/javascript" src="/javascript/jquery-ui-multiselect/src/jquery.multiselect.js"></script>
<script type="text/javascript" src="/javascript/jquery-ui-multiselect/demos/assets/prettify.js"></script>
<script type="text/javascript" src="/javascript/jquery-ui-daterangepicker/jquery.comiseo.daterangepicker.js"></script>
<script type="text/javascript" src="/javascript/moment.js"></script>

<script type="text/javascript" src="/javascript/dailylog.js"></script>
<script type="text/javascript" src="/javascript/timesheet.js"></script>

<title><?PHP echo $dbdescription; ?></title>
</head>
<body>